In [7]:
import pandas as pd
import csv
import re
import sys
sys.path.append('../src/')
from functions import from_tsv_to_list

In [26]:
test_true = from_tsv_to_list('../../Master_gonito/test-A/expected.tsv')

In [4]:
df = pd.read_csv('../model_output/in.csv', index_col=0)

In [28]:
df

,id,true_label,true_box,predicted_label,predicted_box
0,2590,"[3, 3, 3, 3, 3, 3, 0, 3, 3, 0, 0, 0]","[[221.0, 168.0, 322.0, 293.0], [325.0, 399.0, ...","[3, 3, 3, 3, 3, 3, 3]","[[325.154541015625, 399.0157470703125, 373.508..."
1,1763,"[0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, ...","[[125.0, 208.0, 170.0, 273.0], [126.0, 209.0, ...","[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]","[[218.3296356201172, 121.42947387695312, 266.8..."
2,1692,"[0, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6]","[[161.0, 229.0, 208.0, 300.0], [159.0, 29.0, 2...","[6, 6, 6, 5, 5, 6, 6, 5, 6, 6, 5, 6, 5, 5]","[[19.044330596923828, 220.581787109375, 68.506..."
3,229,"[0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, ...","[[98.0, 71.0, 274.0, 146.0], [10.0, 70.0, 98.0...","[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]","[[55.16973876953125, 398.89996337890625, 97.68..."
4,893,"[0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 5]","[[141.0, 33.0, 319.0, 201.0], [8.0, 23.0, 361....","[6, 5, 5, 5, 6, 5, 5, 5]","[[275.1004638671875, 199.6184539794922, 364.20..."
...,...,...,...,...,...
2625,1578,"[0, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, ...","[[166.0, 8.0, 265.0, 126.0], [216.0, 245.0, 36...","[5, 6, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5]","[[116.19573974609375, 104.3750228881836, 163.9..."
2626,171,"[0, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...","[[143.0, 94.0, 186.0, 253.0], [143.0, 28.0, 22...","[6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, ...","[[12.918608665466309, 401.0613098144531, 55.68..."
2627,311,"[2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, ...","[[12.0, 25.0, 111.0, 141.0], [10.0, 143.0, 110...","[5, 5, 5, 6, 6, 5, 6, 6, 5, 5, 5, 6, 5, 5, 6, ...","[[110.76612091064453, 163.0999755859375, 210.0..."
2628,2345,"[0, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, ...","[[14.0, 139.0, 64.0, 211.0], [16.0, 30.0, 64.0...","[5, 6, 6, 6, 6, 6, 5, 5, 6, 6, 6, 6]","[[64.13726806640625, 91.26280212402344, 110.81..."
2629,1218,"[1, 5, 5, 5, 5, 5, 5, 5]","[[215.0, 16.0, 366.0, 227.0], [218.0, 228.0, 3...","[5, 5, 5, 1, 5, 5, 5, 5]","[[10.303159713745117, 214.92507934570312, 60.0..."

In [85]:
final_list = []
for i in range(len(df)):
    pred_labels = df['predicted_label'][i][1:-1].split(',')
    pred_boxes = df['predicted_box'][i][2:-1].split('],')

    for ii in range(len(pred_labels)):
        id = df['id'][i]
        label = pred_labels[ii]
        pred_boxes[ii] = pred_boxes[ii].split(',')
        x0 = int(pred_boxes[ii][0].split('.')[0].replace('[',''))
        y0 = int(pred_boxes[ii][1].split('.')[0].replace('[',''))
        x1 = int(pred_boxes[ii][2].split('.')[0].replace('[',''))
        y1 = int(pred_boxes[ii][3].split('.')[0].replace('[',''))

        final_list.append(id, label, x0, y0, x1, y1)

    break

2590 3 325 399 373 486
2590  3 275 294 375 370
2590  3 272 41 371 162
2590  3 220 167 321 293
2590  3 221 40 272 140
2590  3 224 370 321 484
2590  3 223 298 272 369

In [ ]:
# save list to tsv file
def save_list_to_tsv_file(path, output_list):
    with open(path, 'w', newline='') as f_output: 
        tsv_output = csv.writer(f_output, delimiter='\n')
        tsv_output.writerow(output_list)